# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cdd8e62ec8eec2af6c40dc7b2d5aad325d5b97028653e5d7e102329213f121fbf994b3f1683c1827626c11477375174a8bbf09b605b5f2df494affe9d4f3536

test:
  secret_key_base: 8e835ecbcb032ea43b12b54135911b20d671d4065c15dde0c62078f96961be692004de921d5ed93bde3c6c1cabf5db055762b0e85a681e9affb726b8abd89a2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
